name: libpinproc-linux-x64
on:
  push:
    branches: [ add_workflow_builds ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest  
    strategy:
      matrix:        
        include:        
          - os: ubuntu-14.04
            TARGET: x64
            COMPILER: gcc
            LINKER: gcc       
    steps:    
        - uses: actions/checkout@v2
        - name: Dependencies
          run: |
            sudo apt-get -y install libftdi1 libftdi1-dev zlib1g-dev libudev-dev libusb-dev pkg-config libboost-dev
        - name: Cmake build
          run: |
            mkdir bin;cd bin
            cmake -DBUILD_SHARED_LIBS=ON ..
            make
        - name: Build
          shell: bash
          run: |
              # tag=$(git describe --tags --abbrev=0)
              release_name="libpinproc-dev-2.1-linux-${{ matrix.target }}"        
              7z a -tzip "${release_name}.zip" "/home/runner/work/libpinproc/libpinproc/bin/libpinproc.so" "/home/runner/work/libpinproc/libpinproc/bin/pinproctest" "/home/runner/work/libpinproc/libpinproc/bin/pinprocfw"
              # remove all files apart from the archive
              # rm -rf yes $(ls -I "*.zip" )                
        - name: Publish
          uses: softprops/action-gh-release@v1
          with:
            tag_name: "2.1"
            files: "libpinproc*"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}                 
